In [1]:
import sqlalchemy as db
from sqlalchemy.ext.declarative import declarative_base
import pandas as pd

In [2]:
Username = 'root'
Pass = 'arvin1381'
Server = 'localhost'
engine = db.create_engine(f'mysql+pymysql://{Username}:{Pass}@{Server}:3306/queraprojectdb', echo = True)

conn = engine.connect()
Base = declarative_base()

2023-09-05 17:25:19,475 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2023-09-05 17:25:19,476 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-09-05 17:25:19,478 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2023-09-05 17:25:19,479 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-09-05 17:25:19,480 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2023-09-05 17:25:19,481 INFO sqlalchemy.engine.Engine [raw sql] {}

C:\Users\ROG\AppData\Local\Temp\ipykernel_26880\3073011142.py:7: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [3]:
CoinTag = db.Table('CoinTag', Base.metadata,
                 db.Column('Name', db.String(255), db.ForeignKey('coins.name')),
                 db.Column('Tags', db.String(255), db.ForeignKey('tags.Tags')))

class Coin(Base):
    __tablename__ = 'coins'

    rank = db.Column(db.Integer)
    name = db.Column(db.String(255), primary_key=True)
    symbol = db.Column(db.String(255))
    main_link = db.Column('MainLink',db.String(255))
    historical_link = db.Column('HistoricalLink',db.String(255))
    github_link = db.Column('Github_link',db.String(255))

    tags = db.orm.relationship('Tag', secondary=CoinTag, back_populates='coins')
    coinhistories = db.orm.relationship('CoinHistory', back_populates='coins')

class Tag(Base):
    __tablename__ = 'tags'

    id = db.Column(db.Integer, autoincrement='auto')
    Tags = db.Column(db.String(255),primary_key=True)

    tags = db.orm.relationship('Coin', secondary=CoinTag, back_populates='tags')

class CoinHistory(Base):
    __tablename__ = "coinhistories"

    id = db.Column(db.Integer, primary_key=True, autoincrement='auto')
    name = db.Column(db.String(255), nullable=False)
    Date = db.Column(db.Date)
    open = db.Column(db.Float)
    timeHigh = db.Column(db.Time)
    high = db.Column(db.Float)
    timeLow = db.Column(db.Time)
    low = db.Column(db.Float)
    close = db.Column(db.Float)
    volume = db.Column(db.Float, nullable=False)
    marketCap = db.Column(db.Float, nullable=False)
    DailyPrice = db.Column(db.Float)
    CirculatingSupply = db.Column(db.Float)
    DailyChange = db.Column(db.Float)
    ChangeStatus = db.Column(db.String(255))

    coin = db.orm.relationship('Coin', back_populates='coinhistories')

In [4]:
Base.metadata.create_all(engine)

2023-09-05 17:25:26,406 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-09-05 17:25:26,407 INFO sqlalchemy.engine.Engine DESCRIBE `queraprojectdb`.`CoinTag`
2023-09-05 17:25:26,408 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-09-05 17:25:26,410 INFO sqlalchemy.engine.Engine DESCRIBE `queraprojectdb`.`coins`
2023-09-05 17:25:26,411 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-09-05 17:25:26,412 INFO sqlalchemy.engine.Engine DESCRIBE `queraprojectdb`.`tags`
2023-09-05 17:25:26,413 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-09-05 17:25:26,415 INFO sqlalchemy.engine.Engine DESCRIBE `queraprojectdb`.`coinhistories`
2023-09-05 17:25:26,416 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-09-05 17:25:26,420 INFO sqlalchemy.engine.Engine
CREATE TABLE coins (
	`rank` INTEGER,
	name VARCHAR(255) NOT NULL,
	symbol VARCHAR(255),
	`MainLink` VARCHAR(255),
	`HistoricalLink` VARCHAR(255),
	`Github_link` VARCHAR(255),
	PRIMARY KEY (name)
)


2023-09-05 17:25:26,421 INFO sqlalchemy.engine.Engine [no key 0.00091s] {}
2023-09-05 17:25:26,435 INFO sqlalchemy.engine.Engine
CREATE TABLE tags (
	id INTEGER,
	`Tags` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`Tags`)
)


2023-09-05 17:25:26,436 INFO sqlalchemy.engine.Engine [no key 0.00122s] {}
2023-09-05 17:25:26,451 INFO sqlalchemy.engine.Engine
CREATE TABLE coinhistories (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	`Date` DATE,
	open FLOAT,
	`timeHigh` TIME,
	high FLOAT,
	`timeLow` TIME,
	low FLOAT,
	close FLOAT,
	volume FLOAT NOT NULL,
	`marketCap` FLOAT NOT NULL,
	`DailyPrice` FLOAT,
	`CirculatingSupply` FLOAT,
	`DailyChange` FLOAT,
	`ChangeStatus` VARCHAR(255),
	PRIMARY KEY (id)
)


2023-09-05 17:25:26,452 INFO sqlalchemy.engine.Engine [no key 0.00116s] {}
2023-09-05 17:25:26,467 INFO sqlalchemy.engine.Engine
CREATE TABLE `CoinTag` (
	`Name` VARCHAR(255),
	`Tags` VARCHAR(255),
	FOREIGN KEY(`Name`) REFERENCES coins (name),
	FOREIGN KEY(`Tags`) REFERENCES tags (`Tags`)
)


2023-09-05 17:25:26,468 INFO sqlalchemy.engine.Engine [no key 0.00078s] {}
2023-09-05 17:25:26,487 INFO sqlalchemy.engine.Engine COMMIT

In [5]:
CoinData = pd.read_csv(r'C:\Users\ROG\Desktop\MLBootcamp\Project1\Web Scraping\Finaled\CoinMarketCapNormalised.csv')
CoinData

,Rank,Name,Symbol,MainLink,HistoricalLink,Github_link
0,1,bitcoin,BTC,https://coinmarketcap.com/currencies/bitcoin/,https://coinmarketcap.com/currencies/bitcoin/h...,https://github.com/bitcoin/bitcoin
1,2,ethereum,ETH,https://coinmarketcap.com/currencies/ethereum/,https://coinmarketcap.com/currencies/ethereum/...,https://github.com/ethereum/wiki/wiki/White-Paper
2,3,tether,USDT,https://coinmarketcap.com/currencies/tether/,https://coinmarketcap.com/currencies/tether/hi...,NaN
3,4,bnb,BNB,https://coinmarketcap.com/currencies/bnb/,https://coinmarketcap.com/currencies/bnb/histo...,https://github.com/bnb-chain
4,5,xrp,XRP,https://coinmarketcap.com/currencies/xrp/,https://coinmarketcap.com/currencies/xrp/histo...,https://github.com/ripple/rippled
...,...,...,...,...,...,...
195,196,playdapp,PLA,https://coinmarketcap.com/currencies/playdapp/,https://coinmarketcap.com/currencies/playdapp/...,https://github.com/playdapp
196,197,pundix-new,PUNDIX,https://coinmarketcap.com/currencies/pundix-new/,https://coinmarketcap.com/currencies/pundix-ne...,NaN
197,198,vulcan-forged-pyr,PYR,https://coinmarketcap.com/currencies/vulcan-fo...,https://coinmarketcap.com/currencies/vulcan-fo...,NaN
198,199,status,SNT,https://coinmarketcap.com/currencies/status/,https://coinmarketcap.com/currencies/status/hi...,https://github.com/status-im
199,200,amp,AMP,https://coinmarketcap.com/currencies/amp/,https://coinmarketcap.com/currencies/amp/histo...,https://github.com/amptoken

In [6]:
History = pd.read_csv(r'C:\Users\ROG\Desktop\MLBootcamp\Project1\Web Scraping\Finaled\HistoricalDataProcessed.csv')
History.head(2)

,Name,timeOpen,timeClose,timeHigh,timeLow,open,high,low,close,volume,marketCap,DailyPrice,CirculatingSupply,Date,DailyChange,ChangeStatus
0,Synthetix,2023-08-31T00:00:00.000Z,"""2023-08-31T23:59:59.999Z""","""2023-08-31T12:57:00.000Z""","""2023-08-31T22:14:00.000Z""",1.995606,2.024014,1.923429,1.928386,43897748.10,5.196819e+08,1.928386,2.694905e+08,2023-08-31,-0.067185,Red
1,Synthetix,2023-08-30T00:00:00.000Z,"""2023-08-30T23:59:59.999Z""","""2023-08-30T00:55:00.000Z""","""2023-08-30T23:59:00.000Z""",2.060952,2.084899,1.995572,1.995572,31366413.98,5.372710e+08,1.995572,2.692316e+08,2023-08-30,-0.065396,Red

In [7]:
a = History.groupby(['Name']).last()
a[a['Date']!='2022-09-02']

,timeOpen,timeClose,timeHigh,timeLow,open,high,low,close,volume,marketCap,DailyPrice,CirculatingSupply,Date,DailyChange,ChangeStatus
Name,,,,,,,,,,,,,,,
Aptos,2022-10-19T00:00:00.000Z,"""2022-10-19T23:59:59.999Z""","""2022-10-19T02:01:00.000Z""","""2022-10-19T03:50:00.000Z""",8.384907e+00,8.552428e+00,6.687963e+00,7.240589e+00,1.893697e+09,9.412766e+08,7.240589e+00,1.300000e+08,2022-10-19,7.190102,Green
Arbitrum,2023-03-23T00:00:00.000Z,"""2023-03-23T23:59:59.999Z""","""2023-03-23T13:05:00.000Z""","""2023-03-23T14:29:00.000Z""",1.179699e+01,1.179699e+01,1.104477e+00,1.331082e+00,2.314949e+09,1.697129e+09,1.331082e+00,1.275000e+09,2023-03-23,-98.112151,Red
Axelar,2022-09-27T00:00:00.000Z,"""2022-09-27T23:59:59.999Z""","""2022-09-27T22:19:00.000Z""","""2022-09-27T16:29:00.000Z""",8.165434e-01,1.135992e+00,5.044822e-01,8.580614e-01,1.730782e+07,0.000000e+00,8.580614e-01,0.000000e+00,2022-09-27,0.266590,Green
Binance USD,2022-09-01T00:00:00.000Z,"""2022-09-01T23:59:59.999Z""","""2022-09-01T05:57:00.000Z""","""2022-09-01T15:57:00.000Z""",1.000276e+00,1.000919e+00,9.992963e-01,1.000440e+00,7.713154e+09,1.942708e+10,1.000440e+00,1.941855e+10,2022-09-01,-41.052872,Red
Blur,2023-02-14T00:00:00.000Z,"""2023-02-14T23:59:59.999Z""","""2023-02-14T18:35:00.000Z""","""2023-02-14T18:31:00.000Z""",5.003094e+00,5.192459e+00,4.318308e-01,6.530737e-01,4.552234e+08,2.351065e+08,6.530737e-01,3.600000e+08,2023-02-14,0.423216,Green
Core,2023-02-08T00:00:00.000Z,"""2023-02-08T23:59:59.999Z""","""2023-02-08T12:53:00.000Z""","""2023-02-08T14:40:00.000Z""",4.786658e+00,6.468240e+00,3.855408e+00,4.249438e+00,4.556696e+08,0.000000e+00,4.249438e+00,0.000000e+00,2023-02-08,4.051047,Green
Flare,2023-01-10T00:00:00.000Z,"""2023-01-10T23:59:59.999Z""","""2023-01-10T03:50:00.000Z""","""2023-01-10T04:24:00.000Z""",7.970000e-02,7.970000e-02,2.270000e-02,4.125468e-02,7.308209e+07,0.000000e+00,4.125468e-02,0.000000e+00,2023-01-10,-0.953841,Red
Mantle,2023-07-17T00:00:00.000Z,"""2023-07-17T23:59:59.999Z""","""2023-07-17T23:34:00.000Z""","""2023-07-17T14:12:00.000Z""",4.811910e-01,5.096796e-01,4.674757e-01,5.095311e-01,1.738122e+07,0.000000e+00,5.095311e-01,0.000000e+00,2023-07-17,-2.704167,Red
Pepe,2023-04-17T00:00:00.000Z,"""2023-04-17T23:59:59.999Z""","""2023-04-17T23:06:00.000Z""","""2023-04-17T16:40:00.000Z""",5.685057e-08,7.956576e-08,2.763783e-08,6.637550e-08,4.638521e+07,0.000000e+00,6.637550e-08,0.000000e+00,2023-04-17,-0.831552,Red
Sei,2023-08-15T00:00:00.000Z,"""2023-08-15T23:59:59.999Z""","""2023-08-15T12:10:00.000Z""","""2023-08-15T12:00:00.000Z""",7.989041e-03,2.086169e-01,7.989041e-03,1.776377e-01,2.475806e+08,3.197479e+08,1.776377e-01,1.800000e+09,2023-08-15,-0.067156,Red
Sui,2023-05-03T00:00:00.000Z,"""2023-05-03T23:59:59.999Z""","""2023-05-03T11:52:00.000Z""","""2023-05-03T13:19:00.000Z""",1.717594e+00,1.717594e+00,1.232650e+00,1.403141e+00,1.468656e+09,7.412422e+08,1.403141e+00,5.282737e+08,2023-05-03,1.368099,Green
UniBot,2023-06-16T00:00:00.000Z,"""2023-06-16T23:59:59.999Z""","""2023-06-16T20:31:00.000Z""","""2023-06-16T06:51:00.000Z""",1.786680e+01,2.414322e+01,1.753582e+01,2.116243e+01,9.635202e+05,0.000000e+00,2.116243e+01,0.000000e+00,2023-06-16,20.703254,Green
Worldcoin,2023-07-24T00:00:00.000Z,"""2023-07-24T23:59:59.999Z""","""2023-07-24T09:24:00.000Z""","""2023-07-24T07:24:00.000Z""",1.664895e+00,3.584866e+00,1.664860e+00,2.191566e+00,5.390517e+08,2.331231e+08,2.191566e+00,1.063728e+08,2023-07-24,2.188822,Green

In [8]:
import numpy as np

History = History.drop(columns = ['timeClose','timeOpen'])
History['timeHigh'] = pd.to_datetime(History['timeHigh'].str[13:20]).dt.time
History['timeLow'] = pd.to_datetime(History['timeLow'].str[13:20]).dt.time

History.loc[History.Date == '2022-09-02', ['DailyChange','ChangeStatus']] = 0, 'Gray'

History['DailyChange'] = np.where( ( (History['Name'] == 'Aptos') & (History['Date'] == '2022-10-19')  ) , 0, History['DailyChange'])
History['DailyChange'] = np.where( ( (History['Name'] == 'Arbitrum') & (History['Date'] == '2023-03-23')  ) , 0, History['DailyChange'])
History['DailyChange'] = np.where( ( (History['Name'] == 'Axelar') & (History['Date'] == '2022-09-27')  ) , 0, History['DailyChange'])
History['DailyChange'] = np.where( ( (History['Name'] == 'Binance USD') & (History['Date'] == '2022-09-01')  ) , 0, History['DailyChange'])
History['DailyChange'] = np.where( ( (History['Name'] == 'Blur') & (History['Date'] == '2023-02-14')  ) , 0, History['DailyChange'])
History['DailyChange'] = np.where( ( (History['Name'] == 'Core') & (History['Date'] == '2023-02-08')  ) , 0, History['DailyChange'])
History['DailyChange'] = np.where( ( (History['Name'] == 'Flare') & (History['Date'] == '2023-01-10')  ) , 0, History['DailyChange'])
History['DailyChange'] = np.where( ( (History['Name'] == 'Mantle') & (History['Date'] == '2023-07-17')  ) , 0, History['DailyChange'])
History['DailyChange'] = np.where( ( (History['Name'] == 'Pepe') & (History['Date'] == '2023-04-17')  ) , 0, History['DailyChange'])
History['DailyChange'] = np.where( ( (History['Name'] == 'Sei') & (History['Date'] == '2023-08-15')  ) , 0, History['DailyChange'])
History['DailyChange'] = np.where( ( (History['Name'] == 'Sui') & (History['Date'] == '2023-05-03')  ) , 0, History['DailyChange'])
History['DailyChange'] = np.where( ( (History['Name'] == 'UniBot') & (History['Date'] == '2023-06-16')  ) , 0, History['DailyChange'])
History['DailyChange'] = np.where( ( (History['Name'] == 'Worldcoin') & (History['Date'] == '2023-07-24')  ) , 0, History['DailyChange'])

History['ChangeStatus'] = np.where( ( History['DailyChange'] == 0 ) , 'Gray', History['ChangeStatus'])

History = History[['Name','Date','open','timeHigh','high','timeLow','low','close','volume','DailyPrice','marketCap','CirculatingSupply','DailyChange','ChangeStatus']]

History

C:\Users\ROG\AppData\Local\Temp\ipykernel_26880\3536780808.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  History['timeHigh'] = pd.to_datetime(History['timeHigh'].str[13:20]).dt.time
C:\Users\ROG\AppData\Local\Temp\ipykernel_26880\3536780808.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  History['timeLow'] = pd.to_datetime(History['timeLow'].str[13:20]).dt.time

,Name,Date,open,timeHigh,high,timeLow,low,close,volume,DailyPrice,marketCap,CirculatingSupply,DailyChange,ChangeStatus
0,Synthetix,2023-08-31,1.995606,02:57:00,2.024014,02:14:00,1.923429,1.928386,43897748.10,1.928386,5.196819e+08,2.694905e+08,-0.067185,Red
1,Synthetix,2023-08-30,2.060952,00:55:00,2.084899,03:59:00,1.995572,1.995572,31366413.98,1.995572,5.372710e+08,2.692316e+08,-0.065396,Red
2,Synthetix,2023-08-29,2.080947,04:46:00,2.137082,00:40:00,2.037481,2.060968,45715402.91,2.060968,5.548779e+08,2.692317e+08,-0.020060,Red
3,Synthetix,2023-08-28,2.107940,02:36:00,2.139597,01:46:00,2.079478,2.081028,23323525.55,2.081028,5.600492e+08,2.691214e+08,-0.026909,Red
4,Synthetix,2023-08-27,2.071464,06:44:00,2.148910,00:00:00,2.071464,2.107937,21101866.70,2.107937,5.672910e+08,2.691214e+08,0.036344,Green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70325,Render,2022-09-06,0.500139,02:28:00,0.507269,00:13:00,0.469257,0.469789,9924323.73,0.469789,1.192319e+08,2.537989e+08,-0.030430,Red
70326,Render,2022-09-05,0.516513,00:07:00,0.520092,00:49:00,0.484872,0.500218,10377458.01,0.500218,1.269549e+08,2.537989e+08,-0.016286,Red
70327,Render,2022-09-04,0.509291,03:07:00,0.518565,08:08:00,0.497843,0.516505,4796503.94,0.516505,1.310884e+08,2.537989e+08,0.007291,Green
70328,Render,2022-09-03,0.520313,00:50:00,0.521055,07:55:00,0.501718,0.509214,4426976.60,0.509214,1.292380e+08,2.537989e+08,-0.011092,Red
70329,Render,2022-09-02,0.523143,05:16:00,0.539434,09:40:00,0.509584,0.520306,9301721.24,0.520306,1.320531e+08,2.537989e+08,0.000000,Gray

In [9]:
Tags = pd.read_csv(r'C:\Users\ROG\Desktop\MLBootcamp\Project1\Web Scraping\Finaled\Tags.csv')
Tags = Tags.fillna('Nothing')
Tags = Tags.reset_index()
Tags.rename(columns={'index':'id'}, inplace=True)
Tags

      id                        Tags
0      0                    Mineable
1      1                         PoW
2      2                     SHA-256
3      3                         PoS
4      4             Smart Contracts
..   ...                         ...
123  123  Alameda Research Portfolio
124  124         Everscale Ecosystem
125  125                     Nothing
126  126               Entertainment
127  127          SEC Security Token

[128 rows x 2 columns]

In [10]:
CoinTag = pd.read_csv(r'C:\Users\ROG\Desktop\MLBootcamp\Project1\Web Scraping\Finaled\CoinTagPivot.csv')
CoinTag

         Name                    Tags
0     bitcoin                Mineable
1     bitcoin                     PoW
2     bitcoin                 SHA-256
3    ethereum                     PoS
4    ethereum         Smart Contracts
..        ...                     ...
558    status                   Media
559    status        Content Creation
560    status                 Privacy
561       amp      SEC Security Token
562       amp  Alleged SEC Securities

[563 rows x 2 columns]

In [11]:
CoinData.to_sql(name = 'coins', con = engine, if_exists='append', index = False)
History.to_sql(name = 'coinhistories', con = engine, if_exists='append', index = False)
Tags.to_sql(name = 'tags', con = engine, if_exists='append', index = False)
CoinTag.to_sql(name = 'CoinTag', con = engine, if_exists='append', index = False)

2023-09-05 17:25:56,558 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-09-05 17:25:56,561 INFO sqlalchemy.engine.Engine DESCRIBE `queraprojectdb`.`coins`
2023-09-05 17:25:56,562 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-09-05 17:25:56,570 INFO sqlalchemy.engine.Engine INSERT INTO coins (`Rank`, `Name`, `Symbol`, `MainLink`, `HistoricalLink`, `Github_link`) VALUES (%(Rank)s, %(Name)s, %(Symbol)s, %(MainLink)s, %(HistoricalLink)s, %(Github_link)s)
2023-09-05 17:25:56,571 INFO sqlalchemy.engine.Engine [generated in 0.00243s] [{'Rank': 1, 'Name': 'bitcoin', 'Symbol': 'BTC', 'MainLink': 'https://coinmarketcap.com/currencies/bitcoin/', 'HistoricalLink': 'https://coinmarketcap.com/currencies/bitcoin/historical-data/', 'Github_link': 'https://github.com/bitcoin/bitcoin'}, {'Rank': 2, 'Name': 'ethereum', 'Symbol': 'ETH', 'MainLink': 'https://coinmarketcap.com/currencies/ethereum/', 'HistoricalLink': 'https://coinmarketcap.com/currencies/ethereum/historical-data/', 'Github_link': 'https://github.com/ethereum/wiki/wiki/White-Paper'}, {'Rank': 3, 'Name': 'tether', 'Symbol': 'USDT', 'MainLink': 'https://coinmarketcap.com/currencies/tether/', 'HistoricalLink': 'https://coinmarketcap.com/currencies/tether/historical-data/', 'Github_link': None}, {'Rank': 4, 'Name': 'bnb', 'Symbol': 'BNB', 'MainLink': 'https://coinmarketcap.com/currencies/bnb/', 'HistoricalLink': 'https://coinmarketcap.com/currencies/bnb/historical-data/', 'Github_link': 'https://github.com/bnb-chain'}, {'Rank': 5, 'Name': 'xrp', 'Symbol': 'XRP', 'MainLink': 'https://coinmarketcap.com/currencies/xrp/', 'HistoricalLink': 'https://coinmarketcap.com/currencies/xrp/historical-data/', 'Github_link': 'https://github.com/ripple/rippled'}, {'Rank': 6, 'Name': 'usd-coin', 'Symbol': 'USDC', 'MainLink': 'https://coinmarketcap.com/currencies/usd-coin/', 'HistoricalLink': 'https://coinmarketcap.com/currencies/usd-coin/historical-data/', 'Github_link': 'https://github.com/centrehq/centre-tokens'}, {'Rank': 7, 'Name': 'cardano', 'Symbol': 'ADA', 'MainLink': 'https://coinmarketcap.com/currencies/cardano/', 'HistoricalLink': 'https://coinmarketcap.com/currencies/cardano/historical-data/', 'Github_link': None}, {'Rank': 8, 'Name': 'dogecoin', 'Symbol': 'DOGE', 'MainLink': 'https://coinmarketcap.com/currencies/dogecoin/', 'HistoricalLink': 'https://coinmarketcap.com/currencies/dogecoin/historical-data/', 'Github_link': 'https://github.com/dogecoin/dogecoin/blob/master/README.md'}  ... displaying 10 of 200 total bound parameter sets ...  {'Rank': 199, 'Name': 'status', 'Symbol': 'SNT', 'MainLink': 'https://coinmarketcap.com/currencies/status/', 'HistoricalLink': 'https://coinmarketcap.com/currencies/status/historical-data/', 'Github_link': 'https://github.com/status-im'}, {'Rank': 200, 'Name': 'amp', 'Symbol': 'AMP', 'MainLink': 'https://coinmarketcap.com/currencies/amp/', 'HistoricalLink': 'https://coinmarketcap.com/currencies/amp/historical-data/', 'Github_link': 'https://github.com/amptoken'}]
2023-09-05 17:25:56,587 INFO sqlalchemy.engine.Engine COMMIT
2023-09-05 17:25:56,590 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-09-05 17:25:56,599 INFO sqlalchemy.engine.Engine DESCRIBE `queraprojectdb`.`coinhistories`
2023-09-05 17:25:56,600 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-09-05 17:25:57,566 INFO sqlalchemy.engine.Engine INSERT INTO coinhistories (`Name`, `Date`, open, `timeHigh`, high, `timeLow`, low, close, volume, `DailyPrice`, `marketCap`, `CirculatingSupply`, `DailyChange`, `ChangeStatus`) VALUES (%(Name)s, %(Date)s, %(open)s, %(timeHigh)s, %(high)s, %(timeLow)s, %(low)s, %(close)s, %(volume)s, %(DailyPrice)s, %(marketCap)s, %(CirculatingSupply)s, %(DailyChange)s, %(ChangeStatus)s)
2023-09-05 17:25:57,567 INFO sqlalchemy.engine.Engine [generated in 0.78842s] [{'Name': 'Synthetix', 'Date': '2023-08-31', 'open': 1.9956059654, 'timeHigh': datetime.time(2, 57), 'high': 2.0240140387, 'timeLow': datetime.time(2, 14), 'low': 1.9234289702, 'close': 1.928386385, 'volume': 43897748.1, 'DailyPrice': 1.928386385, 'marketCap': 519681901.34, 'CirculatingSupply': 269490546.80242413, 'DailyChange': -0.0671854589, 'ChangeStatus': 'Red'}, {'Name': 'Synthetix', 'Date': '2023-08-30', 'open': 2.0609516351, 'timeHigh': datetime.time(0, 55), 'high': 2.0848994124, 'timeLow': datetime.time(3, 59), 'low': 1.9955718439, 'close': 1.9955718439, 'volume': 31366413.98, 'DailyPrice': 1.9955718439, 'marketCap': 537270951.54, 'CirculatingSupply': 269231575.491663, 'DailyChange': -0.0653964257999999, 'ChangeStatus': 'Red'}, {'Name': 'Synthetix', 'Date': '2023-08-29', 'open': 2.0809471586, 'timeHigh': datetime.time(4, 46), 'high': 2.1370824864, 'timeLow': datetime.time(0, 40), 'low': 2.0374812599, 'close': 2.0609682697, 'volume': 45715402.91, 'DailyPrice': 2.0609682697, 'marketCap': 554877897.44, 'CirculatingSupply': 269231654.6536496, 'DailyChange': -0.0200601589999998, 'ChangeStatus': 'Red'}, {'Name': 'Synthetix', 'Date': '2023-08-28', 'open': 2.1079400707, 'timeHigh': datetime.time(2, 36), 'high': 2.1395967854, 'timeLow': datetime.time(1, 46), 'low': 2.0794775168, 'close': 2.0810284287, 'volume': 23323525.55, 'DailyPrice': 2.0810284287, 'marketCap': 560049205.46, 'CirculatingSupply': 269121362.1766128, 'DailyChange': -0.0269089564000002, 'ChangeStatus': 'Red'}, {'Name': 'Synthetix', 'Date': '2023-08-27', 'open': 2.0714635355, 'timeHigh': datetime.time(6, 44), 'high': 2.1489104328, 'timeLow': datetime.time(0, 0), 'low': 2.0714635355, 'close': 2.1079373851, 'volume': 21101866.7, 'DailyPrice': 2.1079373851, 'marketCap': 567290980.46, 'CirculatingSupply': 269121362.17608184, 'DailyChange': 0.0363443893999999, 'ChangeStatus': 'Green'}, {'Name': 'Synthetix', 'Date': '2023-08-26', 'open': 2.0624219132, 'timeHigh': datetime.time(5, 6), 'high': 2.0828305954, 'timeLow': datetime.time(0, 55), 'low': 2.0521095393, 'close': 2.0715929957, 'volume': 14078802.77, 'DailyPrice': 2.0715929957, 'marketCap': 557509928.89, 'CirculatingSupply': 269121362.18225384, 'DailyChange': 0.0092352402000002, 'ChangeStatus': 'Green'}, {'Name': 'Synthetix', 'Date': '2023-08-25', 'open': 2.0744321392, 'timeHigh': datetime.time(0, 22), 'high': 2.0753221521, 'timeLow': datetime.time(7, 49), 'low': 2.0201735666, 'close': 2.0623577555, 'volume': 32694877.37, 'DailyPrice': 2.0623577555, 'marketCap': 555024528.46, 'CirculatingSupply': 269121362.1787164, 'DailyChange': -0.0120863470000003, 'ChangeStatus': 'Red'}, {'Name': 'Synthetix', 'Date': '2023-08-24', 'open': 2.1384073241, 'timeHigh': datetime.time(7, 25), 'high': 2.1478869184, 'timeLow': datetime.time(1, 0), 'low': 2.0468532971, 'close': 2.0744441025, 'volume': 26242380.14, 'DailyPrice': 2.0744441025, 'marketCap': 558276703.0, 'CirculatingSupply': 269121111.6882818, 'DailyChange': -0.0638328263999996, 'ChangeStatus': 'Red'}  ... displaying 10 of 70330 total bound parameter sets ...  {'Name': 'Render', 'Date': '2022-09-03', 'open': 0.5203127373, 'timeHigh': datetime.time(0, 50), 'high': 0.5210552923, 'timeLow': datetime.time(7, 55), 'low': 0.501718331, 'close': 0.5092142951, 'volume': 4426976.6, 'DailyPrice': 0.5092142951, 'marketCap': 129238007.45, 'CirculatingSupply': 253798859.7209749, 'DailyChange': -0.0110917431999999, 'ChangeStatus': 'Red'}, {'Name': 'Render', 'Date': '2022-09-02', 'open': 0.5231432319, 'timeHigh': datetime.time(5, 16), 'high': 0.5394339586, 'timeLow': datetime.time(9, 40), 'low': 0.5095841921, 'close': 0.5203060383, 'volume': 9301721.24, 'DailyPrice': 0.5203060383, 'marketCap': 132053079.23, 'CirculatingSupply': 253798859.72774425, 'DailyChange': 0.0, 'ChangeStatus': 'Gray'}]
2023-09-05 17:26:01,798 INFO sqlalchemy.engine.Engine COMMIT
2023-09-05 17:26:01,831 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-09-05 17:26:01,833 INFO sqlalchemy.engine.Engine DESCRIBE `queraprojectdb`.`tags`
2023-09-05 17:26:01,834 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-09-05 17:26:01,839 INFO sqlalchemy.engine.Engine INSERT INTO tags (id, `Tags`) VALUES (%(id)s, %(Tags)s)
2023-09-05 17:26:01,840 INFO sqlalchemy.engine.Engine [generated in 0.00120s] [{'id': 0, 'Tags': 'Mineable'}, {'id': 1, 'Tags': 'PoW'}, {'id': 2, 'Tags': 'SHA-256'}, {'id': 3, 'Tags': 'PoS'}, {'id': 4, 'Tags': 'Smart Contracts'}, {'id': 5, 'Tags': 'Ethereum Ecosystem'}, {'id': 6, 'Tags': 'Payments'}, {'id': 7, 'Tags': 'Stablecoin'}  ... displaying 10 of 128 total bound parameter sets ...  {'id': 126, 'Tags': 'Entertainment'}, {'id': 127, 'Tags': 'SEC Security Token'}]
2023-09-05 17:26:01,844 INFO sqlalchemy.engine.Engine COMMIT
2023-09-05 17:26:01,847 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-09-05 17:26:01,849 INFO sqlalchemy.engine.Engine DESCRIBE `queraprojectdb`.`CoinTag`
2023-09-05 17:26:01,850 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-09-05 17:26:01,859 INFO sqlalchemy.engine.Engine INSERT INTO `CoinTag` (`Name`, `Tags`) VALUES (%(Name)s, %(Tags)s)
2023-09-05 17:26:01,859 INFO sqlalchemy.engine.Engine [generated in 0.00223s] [{'Name': 'bitcoin', 'Tags': 'Mineable'}, {'Name': 'bitcoin', 'Tags': 'PoW'}, {'Name': 'bitcoin', 'Tags': 'SHA-256'}, {'Name': 'ethereum', 'Tags': 'PoS'}, {'Name': 'ethereum', 'Tags': 'Smart Contracts'}, {'Name': 'ethereum', 'Tags': 'Ethereum Ecosystem'}, {'Name': 'tether', 'Tags': 'Payments'}, {'Name': 'tether', 'Tags': 'Stablecoin'}  ... displaying 10 of 563 total bound parameter sets ...  {'Name': 'amp', 'Tags': 'SEC Security Token'}, {'Name': 'amp', 'Tags': 'Alleged SEC Securities'}]
2023-09-05 17:26:01,882 INFO sqlalchemy.engine.Engine SHOW FULL TABLES FROM `queraprojectdb`
2023-09-05 17:26:01,883 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-09-05 17:26:01,886 INFO sqlalchemy.engine.Engine COMMIT

C:\Users\ROG\AppData\Local\Temp\ipykernel_26880\1362912000.py:4: UserWarning: The provided table name 'CoinTag' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  CoinTag.to_sql(name = 'CoinTag', con = engine, if_exists='append', index = False)

563